version: '3'

services:
    alride:
        image: alride:latest
        build: .
        container_name: alride_app
        volumes:
            - ./conf/page_header.en.md:/home/alride/app/config/page_header.en.md:ro
            - ./conf/settings.yml:/home/alride/app/config/settings.local.yml:ro
            - ./data:/home/alride/app/public
            - ./db/production.sqlite3:/home/alride/app/db/production.sqlite3
        ports:
            - 3000:3000
        environment:
            - TZ=Europe/Berlin
        restart: unless-stopped

